//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kji1zeroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otzivi
    {
        public int IdOtziv { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string text { get; set; }
    
        public virtual User User { get; set; }
    }
}
