//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kji1zeroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.User = new HashSet<User>();
        }
    
        public int IdTovar { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Size { get; set; }
        public Nullable<int> IdAge { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> IdCategory { get; set; }
    
        public virtual AgeTovar AgeTovar { get; set; }
        public virtual Category_Tovar Category_Tovar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
