//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kji1zeroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Otzivi = new HashSet<Otzivi>();
        }
    
        public int IdUser { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdTovar { get; set; }
        public Nullable<decimal> Balance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otzivi> Otzivi { get; set; }
        public virtual Role Role { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
